version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 80
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.35
  ambiguity_threshold: 0.10

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_two_stage_clarification"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 80
- name: TEDPolicy
  max_history: 6
  epochs: 100
  constrain_similarities: true
assistant_id: 20260506-125101-flat-deposition
